# site properties and page defaults
title: Li Lab at Louisiana Tech
subtitle: Research on Solid State Materials
description: Our Lab performs interdisciplinary research to synthesize and understand the  structure dynamics of novel solid state materials. Currently we are interested in energy storage materials, quantum materials, and heterocatalysts. We welcome students with backgrounds in chemistry, physics, and (chemical, materials, mechanical) engineering to join us :)
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@solid-li-lab2025.com
  orcid: 0000-0003-0142-7252
  google-scholar: 3i3BkJUAAAAJ&hl
  github: solid-li-lab2025
  twitter: solid-li-lab2025
  youtube: solid-li-lab2025

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "resources"
    values:
      layout: post



      
collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  # generate page for each resource
  resources:
    output: true


# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
