
- id: doi:10.1021/jacs.4c04639
  description: A comprehensive understanding of the structural transformation of DRX cathodes.
  image: https://pubs.acs.org/cms/10.1021/jacs.4c04639/asset/images/large/ja4c04639_0010.jpeg
  tags:
    - Cathode
    - Li-ion Battery 


- id: doi:10.1021/jacs.5c06578
  image: https://pubs.acs.org/cms/10.1021/jacs.5c06578/asset/images/large/ja5c06578_0012.jpeg
  
  
