
- id: doi:10.1021/jacs.4c04639
  description: A comprehensive understanding of the structural transformation of DRX cathodes.
  image: https://pubs.acs.org/cms/10.1021/jacs.4c04639/asset/images/large/ja4c04639_0010.jpeg
  tags:
    - Cathode
    - Li-ion Battery 


  
- id: doi:10.1016/j.nanoen.2017.03.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211285517301404-fx1_lrg.jpg
