
- id: doi:10.1021/jacs.4c04639
  description: A comprehensive understanding of the structural transformation of DRX cathodes.
  image: https://pubs.acs.org/cms/10.1021/jacs.4c04639/asset/images/large/ja4c04639_0010.jpeg
  tags:
    - Cathode
    - Li-ion Battery 


  
- id: doi:10.1016/j.nanoen.2017.03.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211285517301404-fx1_lrg.jpg



- id: doi:10.1021/acs.chemmater.4c02980
  image: https://pubs.acs.org/cms/10.1021/acs.chemmater.4c02980/asset/images/large/cm4c02980_0007.jpeg

- id: doi:10.1021/jacs.5c06578
  image: https://pubs.acs.org/cms/10.1021/jacs.5c06578/asset/images/large/ja5c06578_0012.jpeg

- id: doi:10.1021/acsaem.5c01005
  image: https://pubs.acs.org/cms/10.1021/acsaem.5c01005/asset/images/large/ae5c01005_0007.jpeg


- id: doi:10.1021/acs.chemmater.4c00556
  image: https://pubs.acs.org/cms/10.1021/acs.chemmater.4c00556/asset/images/large/cm4c00556_0012.jpeg

- id: doi:10.1021/acs.jpcc.2c04853
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.2c04853/asset/images/large/jp2c04853_0011.jpeg


- id: doi:10.1021/acsami.1c16668
  image: https://pubs.acs.org/cms/10.1021/acsami.1c16668/asset/images/large/am1c16668_0014.jpeg

  
